<div class="table-responsive">
  <table class="stripe row-border order-column compact" id="marcacionsReport-table">
    <thead>
      <tr>
        <th>N°</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Fecha</th>
        <th>Dia</th>
        <th>H/Entrada</th>
        <th>H/Inicio</th>
        <th>Min</th>
        <th>H/Salida</th>
        <th>H/Fin</th>
        <th>Min</th>
        <th>Min/Ttal(+)</th>
        <th>Min/Ttal(-)</th>
        <th>E/Autorizado</th>
        <th>E/Observacion</th>
        <th>S/Autorizado</th>
        <th>S/Observacion</th>
      </tr>
    </thead>
    <tbody>

    </tbody>
    <tfoot>
      <tr>
        <th>N°</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Fecha</th>
        <th>Dia</th>
        <th>H/Entrada</th>
        <th>H/Inicio</th>
        <th>Min</th>
        <th>H/Salida</th>
        <th>H/Fin</th>
        <th>Min</th>
        <th>Min/Ttal(+)</th>
        <th>Min/Ttal(-)</th>
        <th>E/Autorizado</th>
        <th>E/Observacion</th>
        <th>S/Autorizado</th>
        <th>S/Observacion</th>
      </tr>
    </tfoot>
  </table>
</div>
