<div class="table-responsive">
  <table class="stripe row-border order-column compact" id="recargas-table">
    <thead>
      <tr>
        <th>Accion</th>
        <th>N&deg;Operaci&oacute;n</th>
        <th>Usuario</th>
        <th>Pais</th>
        <th>Banco</th>
        <th>Forma</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Proceso</th>
        <th>Estatus</th>
        <th>Usuario</th>
        <th>Moneda</th>
        <th>Saldo/Prev</th>
        <th>Saldo/Recarga</th>
        <th>Saldo/Final</th>
      </tr>
    </thead>
    <tbody>

    </tbody>
    <tfoot>
      <tr>
        <th>Accion</th>
        <th>N&deg;Operaci&oacute;n</th>
        <th>Usuario</th>
        <th>Pais</th>
        <th>Banco</th>
        <th>Forma</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Proceso</th>
        <th>Estatus</th>
        <th>Usuario</th>
        <th>Moneda</th>
        <th>Saldo/Prev</th>
        <th>Saldo/Recarga</th>
        <th>Saldo/Final</th>
      </tr>
    </tfoot>
  </table>
</div>
